{
 "title": "Firefighters Service Levels Grafana Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Building Areas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"entrance\"}",
     "legendFormat": "Entrance"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"elevator\"}",
     "legendFormat": "Elevator"
    },
    {
     "expr": "kafka_consumergroup_current_offset{topic=\"elevator\",consumergroup=\"building-app\"}",
     "legendFormat": "Apartment"
    }
   ]
  },
  { "title": "SLOs/SLAs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "SLO/SLA Elevator Requests Target",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "99.9" }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.01" }
   ]
  },
  {
   "title": "Burn Rate SLI Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (100 - (sum(delta(camel_exchanges_succeeded_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))/sum(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))) * 100)\n  / \n  (100 - 99.9)\n)"
    }
   ]
  },
  {
   "title": "Burn Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  (100 - (sum(delta(camel_exchanges_succeeded_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))/sum(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))) * 100)\n  / \n  (100 - 99.9)\n)",
     "legendFormat": "Burn Rate for Availability"
    },
    {
     "expr": "(\n  (100 - (count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"} < 0.05 )[5m:])/count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"})[5m:])) * 100)\n  /\n  (100 - 99.9)\n)",
     "legendFormat": "Burn Rate for Latency"
    }
   ]
  },
  { "title": "Elevator Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SLI Elevator Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(camel_exchanges_succeeded_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))/sum(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m])))*100"
    }
   ]
  },
  {
   "title": "SLO Elevator  Requests Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))*0.99"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(delta(camel_exchanges_failed_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))/sum(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m])))*100"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m])*0.01"
    }
   ]
  },
  {
   "title": "Max Elevator Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))"
    }
   ]
  },
  {
   "title": "SLO Elevator Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(camel_exchanges_succeeded_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))/sum(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m])))*100",
     "legendFormat": "Elevator Request SLI"
    }
   ]
  },
  {
   "title": "SLO Elevator Requests Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(camel_exchanges_succeeded_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(delta(camel_exchanges_failed_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m])), 0.1)"
    }
   ]
  },
  {
   "title": "Avg Elevator Max Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(delta(camel_exchanges_total{container=\"mobility-app\", routeId=\"ElevatorProcessing\"}[5m]))"
    }
   ]
  },
  { "title": "Elevator Max Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "SLI Elevator Max Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"} < 0.05 )[5m:])/count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"})[5m:]))*100"
    }
   ]
  },
  {
   "title": "SLO Elevator  Max Time Target",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"})[5m:])*0.99"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"} > 0.05 )[5m:])/count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"})[5m:]))*100"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"})[5m:])*0.01"
    }
   ]
  },
  {
   "title": "Max Elevator Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(elevatorTimerRequest_seconds_sum{camelContext=\"camel-1\", container=\"mobility-app\"}[5m]) / max_over_time(elevatorTimerRequest_seconds_count{camelContext=\"camel-1\", container=\"mobility-app\"}[5m])"
    }
   ]
  },
  {
   "title": "SLO Elevator Timer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(elevatorTimerRequest_seconds_sum{camelContext=\"camel-1\", container=\"mobility-app\"}[5m]) / delta(elevatorTimerRequest_seconds_count{camelContext=\"camel-1\", container=\"mobility-app\"}[5m])",
     "legendFormat": "Elevator Time"
    }
   ]
  },
  {
   "title": "SLO Elevator Requests Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"} < 0.05 )[5m:]))"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count_over_time((elevatorTimerRequest_seconds_max{camelContext=\"camel-1\", container=\"mobility-app\"} > 0.05 )[5m:]))"
    }
   ]
  },
  {
   "title": "Avg Elevator Max Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(elevatorTimerRequest_seconds_sum{camelContext=\"camel-1\", container=\"mobility-app\"}[5m]) / rate(elevatorTimerRequest_seconds_count{camelContext=\"camel-1\", container=\"mobility-app\"}[5m])"
    }
   ]
  }
 ]
}