{
 "title": "Firefighters SRE Grafana Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Areas (Topics)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"lobby\"}",
     "legendFormat": "Lobby"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"entrance\"}",
     "legendFormat": "Entrance"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"elevator\"}",
     "legendFormat": "Elevator"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"stairs\"}",
     "legendFormat": "Stairs"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"exit\"}",
     "legendFormat": "Exit"
    },
    {
     "expr": "kafka_topic_partition_current_offset{topic=\"external\"}",
     "legendFormat": "External"
    },
    {
     "expr": "kafka_consumergroup_current_offset{topic=\"elevator\",consumergroup=\"building-app\"}",
     "legendFormat": "Apartment"
    }
   ]
  },
  {
   "title": "Avg Time from Concierge App to Kafka",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "com_redhat_quarkus_resources_AccessLogResource_processLobbyPostTime_seconds_sum/com_redhat_quarkus_resources_AccessLogResource_processLobbyPostTime_seconds_count",
     "legendFormat": "Concierge App"
    }
   ]
  },
  {
   "title": "Elevator Counter Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(elevatorCounter_total{service=\"mobility-app\"})",
     "legendFormat": "Mobility"
    },
    {
     "expr": "max(elevatorCounter_total{service=\"building-app\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Concierge App",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{container=\"concierge-app\"}"
    }
   ]
  },
  {
   "title": "Mobility",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{container=\"mobility-app\"}"
    }
   ]
  },
  {
   "title": "Building",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_info_total{container=\"building-app\"})"
    }
   ]
  },
  {
   "title": "Avg Time from Mobility to Kafka",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(elevatorTimerRequest_seconds_sum{camelContext=\"camel-1\", container=\"mobility-app\"}[5m]) / rate(elevatorTimerRequest_seconds_count{camelContext=\"camel-1\", container=\"mobility-app\"}[5m])",
     "legendFormat": "Avg Time 5min"
    }
   ]
  },
  {
   "title": "Lags",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"external|lobby|entrance|elevator|stairs|exit\" }) by (topic, consumergroup)",
     "legendFormat": "{{topic}} | {{consumergroup}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Errors Concierge App",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "delta(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\", container=\"concierge-app\"}[60m])"
    }
   ]
  },
  {
   "title": "HTTP Errors Mobility App",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(http_server_errors_total{container=\"mobility-app\"}[60m]))"
    }
   ]
  },
  {
   "title": "HTTP Errors Building",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(http_server_errors_total{container=\"building-app\"}[60m]))"
    }
   ]
  },
  {
   "title": "Avg Time from Building to DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(updateFloorDataTimer_seconds_sum{camelContext=\"camel-1\", container=\"building-app\"}[5m]) / rate(updateFloorDataTimer_seconds_count{camelContext=\"camel-1\", container=\"building-app\"}[5m])",
     "legendFormat": "Avg Time 5min"
    }
   ]
  },
  {
   "title": "Consumer Group Lag (Orders Topic)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"entrace|elevator\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Kafka Errors Concierge App Last Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(kafka_producer_record_error_total{container=\"concierge-app\"}[60m]))"
    }
   ]
  },
  {
   "title": "Fuse Mobility Exchange Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(camel_exchanges_failed_total{service=\"mobility-app\"})"
    }
   ]
  },
  {
   "title": "Fuse Building Exchange Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(camel_exchanges_failed_total{service=\"building-app\"})"
    }
   ]
  },
  {
   "title": "Mobility",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(elevatorCounter_total)", "legendFormat": "Elevator" },
    { "expr": "sum(stairsCounter_total)", "legendFormat": "Stairs" }
   ]
  },
  {
   "title": "HTTP Errors Last 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(http_server_errors_total{container=\"concierge-app\"}[15m]))",
     "legendFormat": "Concierge App"
    },
    {
     "expr": "sum(delta(http_server_errors_total{container=\"mobility-app\"}[15m]))",
     "legendFormat": "Mobility"
    },
    {
     "expr": "sum(delta(http_server_errors_total{container=\"building-app\"}[15m]))",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Mobility",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(elevatorCounter_total)", "legendFormat": "Elevator" },
    { "expr": "sum(stairsCounter_total)", "legendFormat": "Stairs" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 }, "options": { "content": "# 4 Golden Signals" } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_cpu_usage{container=\"concierge-app\"})",
     "legendFormat": "Concierge App"
    },
    {
     "expr": "avg(system_cpu_usage{container=\"fuse-label\"})",
     "legendFormat": "Mobility"
    },
    {
     "expr": "avg(system_cpu_usage{container=\"building-app\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Concierge App",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(http_server_requests_seconds_sum{container=\"concierge-app\",outcome=\"SUCCESS\"}/http_server_requests_seconds_count{container=\"concierge-app\",outcome=\"SUCCESS\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{outcome=\"SUCCESS\"}) by (container)",
     "legendFormat": "SUCCESS {{container}}"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\"}) by (container)",
     "legendFormat": "ERROR {{container}}"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{container=\"concierge-app\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apps Health",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_info_total) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_errors_total{container=\"concierge-app\"})",
     "legendFormat": "Concierge App"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"fuse-label\"})",
     "legendFormat": "Mobility"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"building-app\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Avg Time to Building (window 1 min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(sre_inventory_total_time_seconds_sum) - sum(sre_inventory_total_time_seconds_sum offset 1m)) / (sum(sre_inventory_total_time_seconds_count) - sum(sre_inventory_total_time_seconds_count offset 1m))"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_errors_total{container=\"concierge-app\"})",
     "legendFormat": "Concierge App"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"fuse-label\"})",
     "legendFormat": "Mobility"
    },
    {
     "expr": "sum(http_server_errors_total{container=\"building-app\"})",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Avg Time to Inv",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sre_inventory_total_time_seconds_sum) / sum(sre_inventory_total_time_seconds_count)"
    }
   ]
  },
  {
   "title": "Orders Per App Last Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(application_sre_order_receiver_orders_total) - sum(application_sre_order_receiver_orders_total offset 60m)",
     "legendFormat": "Concierge App"
    },
    {
     "expr": "sum(sre_label_generator_orders_total) - sum(sre_label_generator_orders_total offset 60m)",
     "legendFormat": "Mobility"
    },
    {
     "expr": "sum(sre_inventory_orders_total) - sum(sre_inventory_orders_total offset 60m)",
     "legendFormat": "Building"
    }
   ]
  },
  {
   "title": "Avg Time to Label (window 1 min)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(sre_label_generator_total_time_seconds_sum) - sum(sre_label_generator_total_time_seconds_sum offset 1m)) / (sum(sre_label_generator_total_time_seconds_count) - sum(sre_label_generator_total_time_seconds_count offset 1m))"
    }
   ]
  }
 ]
}